<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Admin extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $user = [
            // Superadmin
            [
                'name' => 'Super Admin',
                'email' => 'superadmin@gmail.com',
                'role_id' => '1',
                'province_id' => null,
                'regency_id' => null,
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Superadmin'),
                'edit_admin_desa' => '1',
                'approve_wisata' => '1',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '1',
            ],
            // Kabupaten
            [
                'name' => 'Kabupaten Madiun',
                'email' => 'madiun@gmail.com',
                'role_id' => '2',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Madiun'),
                'edit_admin_desa' => '1',
                'approve_wisata' => '1',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Kabupaten Pekalongan',
                'email' => 'pekalongan@gmail.com',
                'role_id' => '2',
                'province_id' => '33',
                'regency_id' => '3326',
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Pekalongan'),
                'edit_admin_desa' => '1',
                'approve_wisata' => '1',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Kota Semarang',
                'email' => 'semarang@gmail.com',
                'role_id' => '2',
                'province_id' => '33',
                'regency_id' => '3374',
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Semarang'),
                'edit_admin_desa' => '1',
                'approve_wisata' => '1',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Kota Surakarta',
                'email' => 'surakarta@gmail.com',
                'role_id' => '2',
                'province_id' => '33',
                'regency_id' => '3372',
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Surakarta'),
                'edit_admin_desa' => '1',
                'approve_wisata' => '1',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '0',
            ],
            // Desa
            [
                'name' => 'Desa Kare',
                'email' => 'kare@gmail.com',
                'role_id' => '3',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060003',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Karekare'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Bodag',
                'email' => 'bodag@gmail.com',
                'role_id' => '3',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060001',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Bodagbodag'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Curug Madu',
                'email' => 'curugmadu@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3326',
                'district_id' => '3326060',
                'village_id' => '3326060003',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Curugmadu'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Kepel',
                'email' => 'kepel@gmail.com',
                'role_id' => '3',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060004',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Kepelkepel'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Brumbun',
                'email' => 'brumbun@gmail.com',
                'role_id' => '3',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519050',
                'village_id' => '3519050001',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Brumbun'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Kayupuring',
                'email' => 'kayupuring@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3326',
                'district_id' => '3326040',
                'village_id' => '3326040009',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Kayupuring'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Lolong',
                'email' => 'lolong@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3326',
                'district_id' => '3326070',
                'village_id' => '3326070004',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Lolong'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Pakumbulan',
                'email' => 'pakumbulan@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3326',
                'district_id' => '3326140',
                'village_id' => '3326140005',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Pakumbulan'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Wates',
                'email' => 'wates@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3322',
                'district_id' => '3322010',
                'village_id' => '3322010010',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Wateswates'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            [
                'name' => 'Desa Bejalen',
                'email' => 'bejalen@gmail.com',
                'role_id' => '3',
                'province_id' => '33',
                'regency_id' => '3322',
                'district_id' => '3322100',
                'village_id' => '3322100003',
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Bejalen'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '1',
                'mengajukan_destinasi' => '1',
                'konfirmasi_tiket' => '0',
            ],
            // Destinasi
            [
                'name' => 'Hutan Pinus Nongko Ijo',
                'email' => 'hutanpinusnongkoijo@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060003',
                'destinasi_id' => '1',
                'phone' => '081234567890',
                'password' => bcrypt('!1Hutanpinusnongkoijo'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            [
                'name' => 'Air Terjun Selampir',
                'email' => 'airterjunselampir@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060003',
                'destinasi_id' => '2',
                'phone' => '081234567890',
                'password' => bcrypt('!1Airterjunselampir'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            [
                'name' => 'Agro Wisata Perkebunan Kopi Kandangan',
                'email' => 'perkebunankopikandang@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060003',
                'destinasi_id' => '3',
                'phone' => '081234567890',
                'password' => bcrypt('!1Perkebunankopikandang'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            [
                'name' => 'Aswin Loka Seweru',
                'email' => 'aswinlokaseweru@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060003',
                'destinasi_id' => '4',
                'phone' => '081234567890',
                'password' => bcrypt('!1Aswinlokaseweru'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            [
                'name' => 'Air Terjun Coban Kromo',
                'email' => 'cobankromo@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060001',
                'destinasi_id' => '5',
                'phone' => '081234567890',
                'password' => bcrypt('!1Cobankromo'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            [
                'name' => 'Wana Wisata Selo Gedong',
                'email' => 'selogedong@gmail.com',
                'role_id' => '4',
                'province_id' => '35',
                'regency_id' => '3519',
                'district_id' => '3519060',
                'village_id' => '3519060001',
                'destinasi_id' => '6',
                'phone' => '081234567890',
                'password' => bcrypt('!1Selogedong'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '1',
            ],
            // User
            [
                'name' => 'User 1',
                'email' => 'user@gmail.com',
                'role_id' => '5',
                'province_id' => null,
                'regency_id' => null,
                'district_id' => null,
                'village_id' => null,
                'destinasi_id' => null,
                'phone' => '081234567890',
                'password' => bcrypt('!1Useruser'),
                'edit_admin_desa' => '0',
                'approve_wisata' => '0',
                'tambah_edit_admin_destinasi' => '0',
                'mengajukan_destinasi' => '0',
                'konfirmasi_tiket' => '0',
            ],
        ];

        foreach ($user as $key => $value) {
            User::create($value);
        }
    }
}
